// <auto-generated/>
#pragma warning disable CS0618
using Lod.Client.Api.Item.Spellchecker.Suggestions.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Lod.Client.Api.Item.Spellchecker.Suggestions
{
    /// <summary>
    /// Builds and executes requests for operations under \api\{_locale}\spellchecker\suggestions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SuggestionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Lod.Client.api.item.spellchecker.suggestions.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Lod.Client.Api.Item.Spellchecker.Suggestions.Item.WithWordItemRequestBuilder"/></returns>
        public global::Lod.Client.Api.Item.Spellchecker.Suggestions.Item.WithWordItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("word", position);
                return new global::Lod.Client.Api.Item.Spellchecker.Suggestions.Item.WithWordItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Lod.Client.Api.Item.Spellchecker.Suggestions.SuggestionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SuggestionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/{_locale}/spellchecker/suggestions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Lod.Client.Api.Item.Spellchecker.Suggestions.SuggestionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SuggestionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/{_locale}/spellchecker/suggestions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
